#pragma once

enum XACT_WAVEBANK_WAVEBANK
{
    XACT_WAVEBANK_WAVEBANK_COLLISION_DOVA = 0,
    XACT_WAVEBANK_WAVEBANK_DIED2_DOVA = 1,
    XACT_WAVEBANK_WAVEBANK_JUMP1_DOVA = 2,
    XACT_WAVEBANK_WAVEBANK_JUMP2_DOVA = 3,
    XACT_WAVEBANK_WAVEBANK_PLAY4_DOVA = 4,
    XACT_WAVEBANK_WAVEBANK_SCENE1_DOVA = 5,
    XACT_WAVEBANK_WAVEBANK_SELECT1_DOVA = 6,
    XACT_WAVEBANK_WAVEBANK_SELECT2_DOVA = 7,
    XACT_WAVEBANK_WAVEBANK_SPINCOMBO_DOVA = 8,
    XACT_WAVEBANK_WAVEBANK_TITLE2_DOVA = 9,
};

#define XACT_WAVEBANK_WAVEBANK_ENTRY_COUNT 10
